name: Postman Manual Trigger
on:
  workflow_dispatch:
jobs:
  test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - name: Install newman
          run: npm i newman
        - name: Install reporting
          run: npm i newman-reporter-htmlextra
        - name: Run Postman tests
          run: newman run postman-automation-demo.postman_collection.json --environment postman-automation-demo-env.postman_environment.json -r htmlextra 
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: my-report
            path: ./newman/
            retention-days: 30
