name: Postman Workflow Trigger

on:
  repository_dispatch:
    types: [trigger-workflow]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}
      # current job workflow
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install newman
        run: "npm install -g newman"
      - name: Install reporting
        run: "npm install -g newman-reporter-htmlextra"
      - name: Run Postman tests
        run: "newman run postman-automation-demo.postman_collection.json --environment postman-automation-demo-env.postman_environment.json -r htmlextra" 
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: my-report
          path: ./newman/
          retention-days: 30
